dist: trusty
language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

script: vendor/bin/phpunit

before_script:
    - travis_retry composer self-update
    - travis_retry composer install

cache:
  directories:
    - $HOME/.composer/cache
