#!/bin/bash

git pull


git subtree push -P Application cf-application 2.0
git subtree push -P Base        cf-base        2.0
git subtree push -P Cache       cf-cache       2.0
git subtree push -P Config      cf-config      2.0
git subtree push -P Controller  cf-controller  2.0
git subtree push -P Database    cf-database    2.0
git subtree push -P Http        cf-http        2.0
git subtree push -P Log         cf-log         2.0
git subtree push -P Pattern     cf-pattern     2.0
git subtree push -P Routine     cf-routine     2.0
git subtree push -P Session     cf-session     2.0
git subtree push -P Util        cf-util        2.0
git subtree push -P Validation  cf-validation  2.0
git subtree push -P View        cf-view        2.0
