<?php
namespace Colibri\Validation;

use Exception as PhpException;

class Exception extends PhpException
{
	protected $errors = array();

	/**
	 * @param array $errors
	 * @param \Exception $previous
	 */
	public function __construct(array $errors, PhpException $previous = null)
	{
		parent::__construct("", 0, $previous); // TODO: Change the autogenerated stub
		$this->errors = $errors;
	}

	/**
	 * @return array
	 */
	public function getErrors()
	{
		return $this->errors;
	}
}